Entity Timeline
geovistory/design-system pull request #103
Opened 2023-10-31 09:07 UTC by perrauda

Resolves #54

2024-01-31 14:04 UTC, joschne reviewed
Some considerations:
- The height per row should be ~30px
- The labels of the bar should be left aligned and overflow the bar
- The bar should be of lighter color and the label of dark color
- The X-Axis should be fixed on bottom, in case the chart overflows the height. 
- The tooltip of a bar should shows strange numbers
- The tooltip should show {class label} {entity label} and provide a link to open the temporal entity URI in a new browser tab.

2024-01-31 14:05 UTC, joschne requested changes
I request changes as commented

2024-01-31 14:26 UTC, joschne commented on packages/design-system-web/src/components/geov-timeline-gantt/geov-timeline-gantt.css
I suggest to not set a max-height. This should be responsibility of the container. (Here in PluginTimeline.tsx) I also suggest to set the button to absolute position in top right corner.

:host {
  display: block;
}

.scrollBox {
  overflow-y: auto;
  height: 100%;
}

ion-button {
  position: absolute;
  right: 16px;
  top: 8px;
}

2024-02-16 15:59 UTC, perrauda commented
Now everything is almost functional, except for scrolling for large data. The double axis works, but the real axis is not yet hidden.

2024-03-20 11:08 UTC, joschne requested changes

2024-03-20 11:08 UTC, joschne commented on packages/design-system-web/src/components/geov-timeline-gantt/geov-timeline-gantt.tsx
I would suggest to disable the zoom wheel in favor of normal scroll behavior.

Instead you could add zoom buttons:

```
// in render()
  <div class="gantt-buttons">
    <ion-button size="small" onClick={() => this.resetZoom()}>
      Reset zoom
    </ion-button>
    <ion-button size="small" onClick={() => this.zoomOut()}>
      -
    </ion-button>
    <ion-button size="small" onClick={() => this.zoomIn()}>
      +
    </ion-button>
  </div>
```

```
// in class
  zoomOut() {
    Chart.getChart(this.el).zoom(0.5, 'zoom');
  }
  zoomIn() {
    Chart.getChart(this.el).zoom(1.333333, 'zoom');
  }
```

2024-03-25 14:14 UTC, perrauda commented on packages/design-system-web/src/components/geov-timeline-gantt/geov-timeline-gantt.tsx
> +                    }
Done. Removed the unreachable if. Probably to test with manual data and not from sparql.

2024-04-02 14:40 UTC, joschne approved these changes

2024-04-02 15:02 UTC, merged